### PR TITLE
Support TestNet (?testnet=true)

### PR DESCRIPTION
**Pull request by aafomin**
Basic idea is to add the same functionality for bitcoin TestNet network.
Namely:
 - Generating new paper wallet
 - Sweeping Unspent output
 - Bulk key generation
 - Brain wallet generation
 - Details (By WIF)

Test net is available with additional GET param: ?testnet=true

Examples of output for TestNet:
1) Generating new paper wallet
  Address: 2MtjSdHoySV2a7uQh4UkeVxUfC2RXEUA2AV
  WIF:     cTZxgY7Uc8QPWi9PZ8pFQFkBeBMU4Ydk2vSTdFEhk8FFYUEyJfEE

2) Sweep
  Below transaction are generated with this tool:
  a) P2SH-P2WPKH --> P2SH
   https://testnet.smartbit.com.au/tx/b1cf27db6edf01b3d63cedae6a70f590dabab64d870e67ba11e1b905f7e4f380
  b) P2SH-P2WPKH --> P2PKH
   https://testnet.smartbit.com.au/tx/52791394f0b3a2594c228b4dd909687b2320676660de1142a482e60d9cb4c4b9

3) Bulk keys (Input: 5)
  1, "2N9ufeLsiFBsY2JviwUTFQye5EFiL7UBFi9", "cRA4YPLQmwW342nK6sdm5uH4YkpkMo6bmGjV7P8Wxt8c4WyevkXV"
  2, "2N1soYoevHaTyvinvqwd8ZmQuK2DyxrjFu2", "cRmmGa7gt9oMzWFeikxVhtXQYYokWKvNiY5ye4RgMyjmxo6ekDqn"
  3, "2NCkLPQ6PWbg4fhwpAbRPuTZt46wDaFmZTn", "cUtip1AojJ6jEw7h1VHmPmAdDFNW2NG2cx9XQJwYBojRMckDVvHx"
  4, "2N67ku6R7NU3WHr6H4HS9f34vufbhcXsNC8", "cV9hyxpwHqg84DmoyP2w3tbFuq2dwXqHnkakNW28oRTYF2Y9gMis"
  5, "2N8QU4QR45FVCc9Fe4TXge3rYwXmK6QUBDN", "cW2WYvF2Jpqqd4LospfGpS5DcQUufXMbUSeeeYsYQD7gELmRukUc"

4) Brain wallet (Input: test)
  Address: 2NEnnYkh6PjDQBExLg8PiMCT2BM4n6dp2gS
  WIF:     cSvoPGyKQ26kUCqA3pTu3p7Ehn57tfgWHz2PdWtMS2AirRaFfuDu

5) Details (Input WIF: cUsjsjHey9Dcz2qmLqBmEsKTRPwUe5E51DRLzxgEbgSAtQz6x3r3)
  Address: 2MwP18fcsSuNcM3XBBYE2Hy4fwmwA4dN25K
  PubKey:  03c9d97584b9e3943e0114b1751a27a0a1557a2e353293c4317caa8cae97e07b08
  Redeem:  00147ce495df107167376dc9794c659cdbdc5f377e51

### CODE REVIEW

**Comment by coinables** [comment]
I agree with this concept. Looks good but I'm at work looking on my mobile,
so I can't do much. I'll review and test and report back. Thanks so much
for contributing!

**Comment by aafomin** [comment]
No problem
I had hard time finding segwit wallet generator for Testnet
Thought it might be useful for someone else in the future

**Comment by coinables** [comment]
I agree it's definitely useful. I played with it for a bit last night
everything seems to work okay. I'll likely merge it to master this weekend
assuming there are no issues. Thanks for doing this. I like the idea of
using a get to enable it. I'll probably do the same for a bech 32 version.

**Comment by aafomin** [comment]
Thanks for merging and for fast prod delivery. Great

**Pull request merged**
